# Makefile to compile myprogram with a struct and header file

output: main.o functions.o helper.o
	gcc main.o functions.o helper.o -o output

main.o: main.c functions.h
	gcc -c main.c

functions.o: functions.c functions.h
	gcc -c functions.c

helper.o: helper.c functions.h
	gcc -c helper.c

clean:
	rm -f *.o output
